### ISSUE TITLE
Not able to run MDP_Approx for breakout

### ISSUE THREAD

**Issue by mohit291298** [clvoloshin/OPE-tools#3]
Error:
Epoch 1/100
Traceback (most recent call last):
  File "paper.py", line 1617, in <module>
    main()
  File "paper.py", line 1567, in main
    result = breakout(hyperparam, models, debug)
  File "paper.py", line 1079, in breakout
    mdpmodel = MDPModel.run(env, behavior_data, mbased_num_epochs, batchsize, modeltype)
  File "OPE-tools/ope/models/approximate_model.py", line 398, in run
    use_multiprocessing=False, )
  File ".conda/envs/OPE/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File ".conda/envs/OPE/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File ".conda/envs/OPE/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File ".conda/envs/OPE/lib/python3.6/site-packages/keras/engine/training.py", line 1211, in train_on_batch
    class_weight=class_weight)
  File ".conda/envs/OPE/lib/python3.6/site-packages/keras/engine/training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File ".conda/envs/OPE/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
**ValueError: Error when checking target: expected T to have 4 dimensions, but got array with shape (32, 1, 21168)**

How to fix this issue?

UPDATE:
In Line 328 of file approximate_model.py, it should be 'elif' and not 'if'
Please confirm.

**Comment by clvoloshin** [comment]
Seems like it's taking the state (time, 1, width, height) and modifying it to (time, 1, width * height). You can undo this in the MBased_Approx code.

**Comment by mohit291298** [comment]
I think there is some typing error here in your code (Please confirm!)
![a](https://user-images.githubusercontent.com/29570021/75952792-c4bd3280-5ed5-11ea-8e76-ed215df5bc5e.png)
*In Line 328 of file approximate_model.py, it should be 'elif' and not 'if'*
Please confirm.

**Comment by mohit291298** [comment]
> Seems like it's taking the state (time, 1, width, height) and modifying it to (time, 1, width * height). You can undo this in the MBased_Approx code.

**Comment by mohit291298** [comment]
I think there is some typing error here in your code (Please confirm!)
![image](https://user-images.githubusercontent.com/29570021/76136963-75a20980-605d-11ea-8b36-ddac8accedbf.png)
In Line 328 of file approximate_model.py, it should be 'elif' and not 'if'
Please confirm.

**Comment by mohit291298** [comment]
Please reply!

**Comment by clvoloshin** [comment]
yep pull latest and it's fixed
